name = "cloudflare-docker-proxy"
compatibility_date = "2024-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "coolsec.ai"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
 routes = [
   { pattern = "docker.coolsec.ai", custom_domain = true },
   { pattern = "quay.coolsec.ai", custom_domain = true },
   { pattern = "gcr.coolsec.ai", custom_domain = true },
   { pattern = "k8s-gcr.coolsec.ai", custom_domain = true },
   { pattern = "k8s.coolsec.ai", custom_domain = true },
   { pattern = "ghcr.coolsec.ai", custom_domain = true },
   { pattern = "cloudsmith.coolsec.ai", custom_domain = true },
 ]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.coolsec.ai", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
